"""Synthetic-manifest unit tests for the ``managed`` flag (``tcex update --managed``).

These tests are entirely hand-crafted: they build tiny manifests / cache trees on
``tmp_path`` and never depend on the committed ``tcex-app-templates-v2.zip`` fixture
(which is regenerated by the templates repo and swapped in later). They cover:

* ``Planner.build(managed_only=True)`` routing — managed-and-changed → ``auto_update``,
  managed-and-identical → ``skip``, non-managed → ``skip``, all removed keys → ``skip``
  (with empty ``prompt_user`` and empty ``template_removed`` so ``--managed`` can never
  prompt or delete).
* ``managed_only`` being independent of ``force``.
* ``_build_merged_template`` propagating ``'managed'`` through both the normal and the
  ``.gitignore`` special-case branches (including the ``_app_common`` ``.gitignore`` →
  ``managed: true`` canary).
* ``apply()`` on a ``managed_only`` plan performing copies without raising and deleting
  nothing.
"""

# standard library
import hashlib
import json
from pathlib import Path

# third-party
import pytest

# first-party
from tcex_cli.cli.template.planner import Hasher, ManifestStore, Planner, SafeFileOps
from tcex_cli.cli.template.template_cli import TemplateCli

# ==================================================================
# Helpers
# ==================================================================


def _sha256_bytes(data: bytes) -> str:
    """Return the SHA-256 hex digest of bytes."""
    return hashlib.sha256(data).hexdigest()


def _write_manifest(path: Path, meta: dict) -> None:
    """Write a manifest.json to path."""
    path.write_text(json.dumps(meta, indent=2))


def _make_planner() -> Planner:
    """Return a Planner wired with the real (stateless) collaborators."""
    return Planner(ManifestStore(), Hasher(), SafeFileOps())


def _entry(content: bytes, *, last_commit: str, managed: bool, template_path: str) -> dict:
    """Build a single manifest FileMeta entry for ``content``."""
    return {
        'last_commit': last_commit,
        'sha256': _sha256_bytes(content),
        'template_path': template_path,
        'managed': managed,
    }


# ==================================================================
# Planner.build(managed_only=True) — routing
# ==================================================================
class TestManagedOnlyRouting:
    """``managed_only`` routes keys to skip/auto_update; never prompts or deletes."""

    @staticmethod
    def _build_scenario(tmp_path: Path) -> tuple[Path, Path]:
        """Create a template + project covering every managed_only routing case.

        Template keys:
        * ``managed_changed.py`` — managed, local content differs → auto_update.
        * ``managed_identical.py`` — managed, local content identical → skip.
        * ``unmanaged.py`` — not managed (modified locally) → skip (out of scope).
        Removed-from-template key (present locally, absent in template):
        * ``dropped.py`` — managed in the local manifest, modified on disk → skip
          (``--managed`` never deletes).
        """
        template_dir = tmp_path / 'template'
        project_dir = tmp_path / 'project'
        template_dir.mkdir()
        project_dir.mkdir()

        managed_changed = b'# template managed (new)\n'
        managed_identical = b'# template managed (stable)\n'
        unmanaged = b'# template unmanaged (new)\n'

        (template_dir / 'managed_changed.py').write_bytes(managed_changed)
        (template_dir / 'managed_identical.py').write_bytes(managed_identical)
        (template_dir / 'unmanaged.py').write_bytes(unmanaged)

        template_meta = {
            'managed_changed.py': _entry(
                managed_changed,
                last_commit='c-new',
                managed=True,
                template_path='managed_changed.py',
            ),
            'managed_identical.py': _entry(
                managed_identical,
                last_commit='c-new',
                managed=True,
                template_path='managed_identical.py',
            ),
            'unmanaged.py': _entry(
                unmanaged, last_commit='c-new', managed=False, template_path='unmanaged.py'
            ),
        }
        _write_manifest(template_dir / 'manifest.json', template_meta)

        # local manifest: tracks all three template keys at an older commit plus a
        # key the template no longer ships (dropped.py).
        dropped = b'# old dropped file\n'
        local_meta = {
            'managed_changed.py': _entry(
                b'# old managed content\n',
                last_commit='c-old',
                managed=True,
                template_path='managed_changed.py',
            ),
            'managed_identical.py': _entry(
                managed_identical,
                last_commit='c-old',
                managed=True,
                template_path='managed_identical.py',
            ),
            'unmanaged.py': _entry(
                b'# old unmanaged content\n',
                last_commit='c-old',
                managed=False,
                template_path='unmanaged.py',
            ),
            'dropped.py': _entry(
                dropped, last_commit='c-old', managed=True, template_path='dropped.py'
            ),
        }
        _write_manifest(project_dir / 'manifest.json', local_meta)

        # on-disk local files
        (project_dir / 'managed_changed.py').write_bytes(b'# old managed content\n')
        (project_dir / 'managed_identical.py').write_bytes(managed_identical)
        (project_dir / 'unmanaged.py').write_bytes(b'# user edits to unmanaged\n')
        (project_dir / 'dropped.py').write_bytes(b'# user edits to dropped\n')

        return template_dir, project_dir

    def test_managed_changed_goes_to_auto_update(self, tmp_path):
        """A managed file whose local hash differs from the template → auto_update."""
        template_dir, project_dir = self._build_scenario(tmp_path)
        plan = _make_planner().build(template_dir, project_dir, managed_only=True)

        assert ('managed_changed.py', 'managed_changed.py') in plan.auto_update
        assert ('managed_changed.py', 'managed_changed.py') not in plan.skip

    def test_managed_identical_skips(self, tmp_path):
        """A managed file already matching the template hash → skip (no rewrite)."""
        template_dir, project_dir = self._build_scenario(tmp_path)
        plan = _make_planner().build(template_dir, project_dir, managed_only=True)

        assert ('managed_identical.py', 'managed_identical.py') in plan.skip
        assert ('managed_identical.py', 'managed_identical.py') not in plan.auto_update

    def test_unmanaged_skips(self, tmp_path):
        """A non-managed file (even if locally modified) → skip (out of scope)."""
        template_dir, project_dir = self._build_scenario(tmp_path)
        plan = _make_planner().build(template_dir, project_dir, managed_only=True)

        assert ('unmanaged.py', 'unmanaged.py') in plan.skip
        assert ('unmanaged.py', 'unmanaged.py') not in plan.auto_update

    def test_removed_key_skips(self, tmp_path):
        """A key removed from the template → skip (never appended to template_removed)."""
        template_dir, project_dir = self._build_scenario(tmp_path)
        plan = _make_planner().build(template_dir, project_dir, managed_only=True)

        assert ('dropped.py', 'dropped.py') in plan.skip
        assert ('dropped.py', 'dropped.py') not in plan.auto_update

    def test_never_prompts_and_never_removes(self, tmp_path):
        """``--managed`` can never prompt or delete: both lists are empty."""
        template_dir, project_dir = self._build_scenario(tmp_path)
        plan = _make_planner().build(template_dir, project_dir, managed_only=True)

        assert plan.prompt_user == [], 'managed_only must never populate prompt_user'
        assert plan.template_removed == [], 'managed_only must never populate template_removed'


# ==================================================================
# Planner.build — managed_only is independent of force
# ==================================================================
class TestManagedOnlyIndependentOfForce:
    """``managed_only`` routing is identical with ``force=True`` and ``force=False``."""

    @staticmethod
    def _build(tmp_path: Path) -> tuple[Path, Path]:
        """Template + project: one managed-changed file and one unmanaged file."""
        template_dir = tmp_path / 'template'
        project_dir = tmp_path / 'project'
        template_dir.mkdir()
        project_dir.mkdir()

        managed_new = b'# managed new\n'
        unmanaged_new = b'# unmanaged new\n'
        (template_dir / 'managed.py').write_bytes(managed_new)
        (template_dir / 'unmanaged.py').write_bytes(unmanaged_new)

        template_meta = {
            'managed.py': _entry(
                managed_new, last_commit='c-new', managed=True, template_path='managed.py'
            ),
            'unmanaged.py': _entry(
                unmanaged_new, last_commit='c-new', managed=False, template_path='unmanaged.py'
            ),
        }
        _write_manifest(template_dir / 'manifest.json', template_meta)

        local_meta = {
            'managed.py': _entry(
                b'# managed old\n', last_commit='c-old', managed=True, template_path='managed.py'
            ),
            'unmanaged.py': _entry(
                b'# unmanaged old\n',
                last_commit='c-old',
                managed=False,
                template_path='unmanaged.py',
            ),
        }
        _write_manifest(project_dir / 'manifest.json', local_meta)

        (project_dir / 'managed.py').write_bytes(b'# managed old\n')
        (project_dir / 'unmanaged.py').write_bytes(b'# unmanaged old\n')

        return template_dir, project_dir

    @pytest.mark.parametrize(
        argnames='force',
        argvalues=[
            pytest.param(False, id='force-false'),
            pytest.param(True, id='force-true'),
        ],
    )
    def test_managed_routing_unaffected_by_force(self, tmp_path, force):
        """The managed_only plan is the same regardless of the ``force`` flag."""
        template_dir, project_dir = self._build(tmp_path)
        plan = _make_planner().build(template_dir, project_dir, force=force, managed_only=True)

        # managed file routed to auto_update; unmanaged skipped; force had no effect
        assert ('managed.py', 'managed.py') in plan.auto_update
        assert ('unmanaged.py', 'unmanaged.py') in plan.skip
        assert ('unmanaged.py', 'unmanaged.py') not in plan.auto_update
        assert plan.prompt_user == []
        assert plan.template_removed == []


# ==================================================================
# Planner.apply — managed_only plan copies, raises nothing, deletes nothing
# ==================================================================
class TestManagedOnlyApply:
    """Applying a managed_only plan performs copies and removes no files."""

    def test_apply_copies_without_raising_and_deletes_nothing(self, tmp_path):
        """auto_update copies the managed file; a sibling on disk is left untouched."""
        template_dir = tmp_path / 'template'
        project_dir = tmp_path / 'project'
        template_dir.mkdir()
        project_dir.mkdir()

        managed_new = b'# managed new\n'
        (template_dir / 'managed.py').write_bytes(managed_new)
        _write_manifest(
            template_dir / 'manifest.json',
            {
                'managed.py': _entry(
                    managed_new, last_commit='c-new', managed=True, template_path='managed.py'
                )
            },
        )

        _write_manifest(
            project_dir / 'manifest.json',
            {
                'managed.py': _entry(
                    b'# managed old\n',
                    last_commit='c-old',
                    managed=True,
                    template_path='managed.py',
                )
            },
        )
        (project_dir / 'managed.py').write_bytes(b'# managed old\n')
        # an untracked local file that must survive the apply()
        (project_dir / 'keep_me.py').write_bytes(b'# untouched local file\n')

        planner = _make_planner()
        plan = planner.build(template_dir, project_dir, managed_only=True)

        # apply returns None and must not raise (no removals to crash on)
        result = planner.apply(plan, template_root=template_dir, project_root=project_dir)
        assert result is None

        # managed file copied from template; sibling untouched; nothing deleted
        assert (project_dir / 'managed.py').read_bytes() == managed_new
        assert (project_dir / 'keep_me.py').read_bytes() == b'# untouched local file\n'


# ==================================================================
# _build_merged_template — propagates 'managed' (normal + .gitignore branch)
# ==================================================================
class TestBuildMergedTemplateManaged:
    """``_build_merged_template`` copies ``managed`` into both manifest branches."""

    @staticmethod
    def _make_cli(tmp_path: Path) -> TemplateCli:
        """Return a TemplateCli with cli_out_path pinned under tmp_path."""
        cli = TemplateCli(proxy_host=None, proxy_port=None, proxy_user=None, proxy_pass=None)
        cli.__dict__['cli_out_path'] = tmp_path / '.tcex'
        return cli

    @staticmethod
    def _build_cache(cache_dir: Path) -> None:
        """Hand-build a minimal cache: ``_app_common`` parent + ``playbook/basic`` leaf.

        ``_app_common`` ships:
        * ``pyproject.toml`` (managed boilerplate, normal branch)
        * ``app.py`` (unmanaged app logic, normal branch)
        * ``gitignore`` (managed boilerplate, renamed → ``.gitignore`` special case)
        ``playbook/basic`` ships:
        * ``playbook_app.py`` (managed scaffold, normal branch)
        """
        common = cache_dir / '_app_common'
        leaf = cache_dir / 'playbook' / 'basic'
        common.mkdir(parents=True)
        leaf.mkdir(parents=True)

        # --- _app_common files + manifest ---
        pyproject = b'[project]\nname = "x"\n'
        app_py = b'# app logic\n'
        gitignore = b'*.pyc\n__pycache__/\n'
        (common / 'pyproject.toml').write_bytes(pyproject)
        (common / 'app.py').write_bytes(app_py)
        (common / 'gitignore').write_bytes(gitignore)
        (common / 'template.yaml').write_text(
            'contributor: tc\ndescription: app common\nsummary: app common\nversion: 1.0.0\n'
            'template_files:\n  - pyproject.toml\n  - gitignore\n'
        )
        common_manifest = {
            'pyproject.toml': _entry(
                pyproject, last_commit='c1', managed=True, template_path='pyproject.toml'
            ),
            'app.py': _entry(app_py, last_commit='c1', managed=False, template_path='app.py'),
            # the renamed gitignore is recorded under the dotted key with managed=True
            '.gitignore': _entry(
                gitignore, last_commit='c1', managed=True, template_path='.gitignore'
            ),
        }
        _write_manifest(common / 'manifest.json', common_manifest)

        # --- playbook/basic files + manifest ---
        playbook_app = b'# playbook scaffold\n'
        (leaf / 'playbook_app.py').write_bytes(playbook_app)
        (leaf / 'template.yaml').write_text(
            'contributor: tc\ndescription: basic\nsummary: basic\nversion: 1.0.0\n'
            'template_parents:\n  - _app_common\n'
            'template_files:\n  - playbook_app.py\n'
        )
        leaf_manifest = {
            'playbook_app.py': _entry(
                playbook_app, last_commit='c1', managed=True, template_path='playbook_app.py'
            ),
        }
        _write_manifest(leaf / 'manifest.json', leaf_manifest)

    @staticmethod
    def _cleanup(merged_dir: Path) -> None:
        """Remove a caller-owned merged temp dir."""
        for p in sorted(merged_dir.rglob('*'), reverse=True):
            p.unlink() if p.is_file() else p.rmdir()
        merged_dir.rmdir()

    def _merged_manifest(self, tmp_path: Path) -> dict:
        """Build the merged template from the synthetic cache and return its manifest."""
        cli = self._make_cli(tmp_path)
        cache_dir = tmp_path / 'cache'
        cache_dir.mkdir()
        self._build_cache(cache_dir)

        merged_dir = cli._build_merged_template(cache_dir, 'basic', 'playbook')
        try:
            return json.loads((merged_dir / 'manifest.json').read_text())
        finally:
            self._cleanup(merged_dir)

    def test_normal_branch_propagates_managed_true(self, tmp_path):
        """A managed parent file keeps ``managed: true`` in the merged manifest."""
        manifest = self._merged_manifest(tmp_path)
        assert manifest['pyproject.toml']['managed'] is True

    def test_normal_branch_propagates_managed_false(self, tmp_path):
        """An unmanaged parent file keeps ``managed: false`` in the merged manifest."""
        manifest = self._merged_manifest(tmp_path)
        assert manifest['app.py']['managed'] is False

    def test_leaf_branch_propagates_managed_true(self, tmp_path):
        """A managed leaf (child) file keeps ``managed: true`` in the merged manifest."""
        manifest = self._merged_manifest(tmp_path)
        assert manifest['playbook_app.py']['managed'] is True

    def test_gitignore_special_case_propagates_managed_true(self, tmp_path):
        """The renamed ``_app_common`` ``.gitignore`` resolves to ``managed: true``.

        Finding-#2/#3 regression canary: the special-case branch must read
        ``managed`` from the same parent entry it reuses for ``last_commit``.
        """
        manifest = self._merged_manifest(tmp_path)
        assert manifest['.gitignore']['managed'] is True
        # template_path is the dotted project-relative name
        assert manifest['.gitignore']['template_path'] == '.gitignore'
